import os
from setuptools import find_packages, setup


with open("README.md", "r") as f:
    long_description = f.read()

with open("requirements.txt", "r") as f:
    install_requires = f.read().splitlines()

version = "0.0.1"

with open(os.path.join("de", "version.py"), "w") as f:
    f.writelines([
        '"""This file is auto-generated by setup.py, please do not alter."""\n',
        f'__version__ = "{version}"\n',
        "",
    ])


setup(
    name="de",
    version=version,
    description="Machine Learning-guided Directed Evolution for Protein Design.",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/HySonLab/Directed_Evolution",
    packages=find_packages(),
    install_requires=install_requires,
    python_requires=">=3.10",
    license="GNU",
    keywords=["directed evolution", "protein engineering"]
)
